// shared/services/mockData.ts
// Comprehensive mock data covering all use cases and edge cases for the promoter portal.
// All data is linked (job → shift → payment) and includes multiple promoters with different statuses.

import type { UserProfile }  from '../types/user.types';
import type { Job }           from '../types/job.types';
import type { Shift }         from '../types/shift.types';
import type { Payment }       from '../types/payment.types';

// ─── Profiles ─────────────────────────────────────────────────────────────────
// Promoters with various onboarding statuses
export interface UserProfileWithEmail extends UserProfile {
  email: string;
}

export const MOCK_PROFILES: UserProfileWithEmail[] = [
  // Approved promoter with complete data
  {
    userId:      'p-001',
    email:       'lebo@honeygroup.co.za',
    fullName:    'Lebo Mokoena',
    idNumber:    '0001125034567',
    dateOfBirth: '2000-01-12',
    gender:      'female',
    address:     '7 Nelson Mandela Square',
    city:        'Sandton',
    province:    'Gauteng',
    physicalAttributes: { height: 172, clothingSize: 'M', shoeSize: '6' },
    documents: {
      idFront: 'mock://id_front.jpg', idBack: 'mock://id_back.jpg',
      taxNumber: '9876543210', bankConfirmation: 'mock://bank_letter.pdf',
      cv: 'mock://cv.pdf', profilePhotos: ['mock://photo1.jpg'],
    },
    bankDetails: { bankName: 'Capitec', accountNumber: '1234567890', accountType: 'Savings', branchCode: '470010' },
    reliabilityScore: 4.2,
    onboardingStatus: 'approved',
    profilePhoto: 'https://i.pravatar.cc/150?img=32',
    socialMedia: { instagram: '@lebo_promo', tiktok: '@lebopromo' },
    createdAt: '2024-10-15T07:00:00Z',
    updatedAt: '2024-10-20T09:00:00Z',
  },
  // Approved promoter with lower reliability score
  {
    userId:      'p-002',
    email:       'thabo@honeygroup.co.za',
    fullName:    'Thabo Nkosi',
    idNumber:    '9505105034567',
    dateOfBirth: '1995-05-10',
    gender:      'male',
    address:     '14 Commissioner Street',
    city:        'Johannesburg',
    province:    'Gauteng',
    physicalAttributes: { height: 182, clothingSize: 'L', shoeSize: '10' },
    documents: {
      idFront: 'mock://id_front2.jpg', idBack: 'mock://id_back2.jpg',
      taxNumber: '1234567890', bankConfirmation: 'mock://bank2.pdf',
      cv: 'mock://cv2.pdf', profilePhotos: [],
    },
    bankDetails: { bankName: 'FNB', accountNumber: '9876543210', accountType: 'Cheque', branchCode: '250655' },
    reliabilityScore: 3.8,
    onboardingStatus: 'approved',
    profilePhoto: 'https://i.pravatar.cc/150?img=12',
    socialMedia: { instagram: '@thabo_sa' },
    createdAt: '2024-09-01T08:00:00Z',
    updatedAt: '2024-09-10T08:00:00Z',
  },
  // Pending promoter
  {
    userId:      'p-003',
    email:       'nomsa@honeygroup.co.za',
    fullName:    'Nomsa Zulu',
    idNumber:    '9902034567890',
    dateOfBirth: '1999-02-03',
    gender:      'female',
    address:     '22 Beach Road',
    city:        'Cape Town',
    province:    'Western Cape',
    physicalAttributes: { height: 165, clothingSize: 'S', shoeSize: '5' },
    documents: {
      idFront: 'mock://id_front3.jpg', idBack: 'mock://id_back3.jpg',
      taxNumber: '5551234567', bankConfirmation: 'mock://bank3.pdf',
      cv: 'mock://cv3.pdf', profilePhotos: [],
    },
    bankDetails: { bankName: 'Standard Bank', accountNumber: '555000111', accountType: 'Savings', branchCode: '020909' },
    reliabilityScore: 0,
    onboardingStatus: 'pending_review',
    profilePhoto: 'https://i.pravatar.cc/150?img=45',
    socialMedia: { instagram: '@nomsa_ct' },
    createdAt: '2026-03-10T10:00:00Z',
    updatedAt: '2026-03-10T10:00:00Z',
  },
  // Rejected promoter with reason
  {
    userId:      'p-004',
    email:       'siya@honeygroup.co.za',
    fullName:    'Siyabonga Dlamini',
    idNumber:    '8807123456789',
    dateOfBirth: '1988-07-12',
    gender:      'male',
    address:     '55 Main Road',
    city:        'Durban',
    province:    'KwaZulu-Natal',
    physicalAttributes: { height: 175, clothingSize: 'L', shoeSize: '9' },
    documents: {
      idFront: 'mock://id_front4.jpg', idBack: 'mock://id_back4.jpg',
      taxNumber: '7778889990', bankConfirmation: 'mock://bank4.pdf',
      cv: 'mock://cv4.pdf', profilePhotos: [],
    },
    bankDetails: { bankName: 'Nedbank', accountNumber: '444555666', accountType: 'Cheque', branchCode: '198765' },
    reliabilityScore: 0,
    onboardingStatus: 'rejected',
    rejectionReason: 'ID document blurry, please re-upload clear photos.',
    profilePhoto: 'https://i.pravatar.cc/150?img=60',
    socialMedia: { instagram: '@siya_dbn' },
    createdAt: '2026-03-08T09:00:00Z',
    updatedAt: '2026-03-09T14:00:00Z',
  },
  // Blacklisted promoter
  {
    userId:      'p-005',
    email:       'zandile@honeygroup.co.za',
    fullName:    'Zandile Khumalo',
    idNumber:    '9201011234567',
    dateOfBirth: '1992-01-01',
    gender:      'female',
    address:     '12 Main Street',
    city:        'Pretoria',
    province:    'Gauteng',
    physicalAttributes: { height: 168, clothingSize: 'M', shoeSize: '7' },
    documents: {
      idFront: 'mock://id_front5.jpg', idBack: 'mock://id_back5.jpg',
      taxNumber: '1112223334', bankConfirmation: 'mock://bank5.pdf',
      cv: 'mock://cv5.pdf', profilePhotos: [],
    },
    bankDetails: { bankName: 'Absa', accountNumber: '999888777', accountType: 'Savings', branchCode: '632005' },
    reliabilityScore: 1.2,
    onboardingStatus: 'blacklisted',
    profilePhoto: 'https://i.pravatar.cc/150?img=25',
    socialMedia: { instagram: '@zandile_pta' },
    createdAt: '2025-11-01T08:00:00Z',
    updatedAt: '2026-02-15T11:00:00Z',
  },
  // Incomplete promoter (registered but not finished)
  {
    userId:      'p-006',
    email:       'karabo@honeygroup.co.za',
    fullName:    'Karabo Moloi',
    idNumber:    '',
    dateOfBirth: '',
    gender:      'female',
    address:     '',
    city:        '',
    province:    '',
    physicalAttributes: { height: 0, clothingSize: '' },
    documents: { profilePhotos: [] },
    reliabilityScore: 0,
    onboardingStatus: 'incomplete',
    profilePhoto: 'https://i.pravatar.cc/150?img=50',
    socialMedia: {},
    createdAt: '2026-03-11T12:00:00Z',
    updatedAt: '2026-03-11T12:00:00Z',
  },
];

// ─── Jobs ─────────────────────────────────────────────────────────────────────
// Jobs with various filters, statuses, and locations
export const MOCK_JOBS: Job[] = [
  // Open job with female + height filter
  {
    id: 'j-001',
    title: 'Castle Lite Brand Activator',
    client: 'AB InBev',
    brand: 'Castle Lite',
    venue: 'Sandton City Mall',
    address: '163 Fifth St, Sandhurst, Sandton',
    coordinates: { lat: -26.1076, lng: 28.0560 },
    date: '2025-07-12',
    startTime: '18:00',
    endTime: '22:00',
    hourlyRate: 120,
    totalSlots: 4,
    filledSlots: 2,
    filters: { gender: 'female', minHeight: 160 },
    status: 'open',
    distanceKm: 63.2,
    createdBy: 'admin-001',
    createdAt: '2025-07-01T08:00:00Z',
  },
  // Filled job (no slots left)
  {
    id: 'j-002',
    title: 'Vodacom Promo Specialist',
    client: 'Vodacom',
    brand: 'Vodacom',
    venue: 'Rosebank Mall',
    address: 'The Zone, Oxford Rd, Rosebank',
    coordinates: { lat: -26.1461, lng: 28.0438 },
    date: '2025-07-15',
    startTime: '09:00',
    endTime: '17:00',
    hourlyRate: 100,
    totalSlots: 6,
    filledSlots: 6,
    filters: { gender: 'any' },
    status: 'filled',
    distanceKm: 7.1,
    createdBy: 'admin-001',
    createdAt: '2025-07-02T08:00:00Z',
  },
  // Open job with female only (no height)
  {
    id: 'j-003',
    title: 'Amarula Experiential Hostess',
    client: 'Distell',
    brand: 'Amarula',
    venue: 'Hyde Park Corner',
    address: 'Jan Smuts Ave, Hyde Park',
    coordinates: { lat: -26.1223, lng: 28.0371 },
    date: '2025-07-18',
    startTime: '17:00',
    endTime: '21:00',
    hourlyRate: 130,
    totalSlots: 3,
    filledSlots: 1,
    filters: { gender: 'female', minHeight: 165 },
    status: 'open',
    distanceKm: 5.4,
    createdBy: 'admin-001',
    createdAt: '2025-07-03T08:00:00Z',
  },
  // Open job with any gender
  {
    id: 'j-004',
    title: 'MTN Street Team Member',
    client: 'MTN',
    brand: 'MTN',
    venue: 'Eastgate Shopping Centre',
    address: '43 Bradford Rd, Bedfordview',
    coordinates: { lat: -26.1778, lng: 28.1214 },
    date: '2025-07-20',
    startTime: '10:00',
    endTime: '16:00',
    hourlyRate: 95,
    totalSlots: 8,
    filledSlots: 3,
    filters: { gender: 'any' },
    status: 'open',
    distanceKm: 14.8,
    createdBy: 'admin-001',
    createdAt: '2025-07-04T08:00:00Z',
  },
  // Open job with male only + height
  {
    id: 'j-006',
    title: 'Heineken Brand Ambassador',
    client: 'Heineken',
    brand: 'Heineken',
    venue: 'V&A Waterfront',
    address: 'Dock Rd, Cape Town',
    coordinates: { lat: -33.9055, lng: 18.4197 },
    date: '2025-07-30',
    startTime: '14:00',
    endTime: '22:00',
    hourlyRate: 150,
    totalSlots: 2,
    filledSlots: 0,
    filters: { gender: 'male', minHeight: 175 },
    status: 'open',
    distanceKm: 0, // will be computed based on user location
    createdBy: 'admin-001',
    createdAt: '2025-07-10T08:00:00Z',
  },
  // Completed job (past date)
  {
    id: 'j-007',
    title: 'Savanna Tasting Event',
    client: 'Distell',
    brand: 'Savanna',
    venue: 'Gateway Theatre',
    address: '15 Palm Blvd, Umhlanga',
    coordinates: { lat: -29.7223, lng: 31.0766 },
    date: '2025-06-25',
    startTime: '12:00',
    endTime: '20:00',
    hourlyRate: 110,
    totalSlots: 5,
    filledSlots: 5,
    filters: { gender: 'any' },
    status: 'completed',
    distanceKm: 12.0,
    createdBy: 'admin-001',
    createdAt: '2025-06-10T08:00:00Z',
  },
  // Cancelled job
  {
    id: 'j-008',
    title: 'Red Bull Can Collection',
    client: 'Red Bull',
    brand: 'Red Bull',
    venue: 'Menlyn Park',
    address: 'Atterbury Rd, Pretoria',
    coordinates: { lat: -25.7845, lng: 28.2742 },
    date: '2025-07-05',
    startTime: '09:00',
    endTime: '17:00',
    hourlyRate: 130,
    totalSlots: 4,
    filledSlots: 1,
    filters: { gender: 'any' },
    status: 'cancelled',
    distanceKm: 10.5,
    createdBy: 'admin-001',
    createdAt: '2025-06-20T08:00:00Z',
  },
];

// ─── Shifts ───────────────────────────────────────────────────────────────────
// Shifts for various promoters, covering all shift statuses
export const MOCK_SHIFTS: Shift[] = [
  // Completed & approved shift for p-001
  {
    id: 's-001',
    jobId: 'j-001',
    promoterId: 'p-001',
    attendance: {
      shiftId: 's-001',
      promoterId: 'p-001',
      jobId: 'j-001',
      checkInTime: '2025-06-28T18:02:00Z',
      checkInLocation: { lat: -26.1076, lng: 28.056, accuracy: 12, timestamp: '2025-06-28T18:02:00Z' },
      checkInSelfie: 'mock://selfie1.jpg',
      checkOutTime: '2025-06-28T22:05:00Z',
      checkOutLocation: { lat: -26.1076, lng: 28.056, accuracy: 8, timestamp: '2025-06-28T22:05:00Z' },
      checkOutSelfie: 'mock://selfie1_out.jpg',
      totalHours: 4.05,
      issues: [],
      supervisorRating: 5,
      status: 'approved',
    },
    grossPay: 486,
    deductions: 0,
    netPay: 486,
    status: 'approved',
  },
  // Pending approval shift (with issue)
  {
    id: 's-002',
    jobId: 'j-002',
    promoterId: 'p-001',
    attendance: {
      shiftId: 's-002',
      promoterId: 'p-001',
      jobId: 'j-002',
      checkInTime: '2025-07-05T09:10:00Z',
      checkInLocation: { lat: -26.1461, lng: 28.0438, accuracy: 15, timestamp: '2025-07-05T09:10:00Z' },
      checkInSelfie: 'mock://selfie2.jpg',
      checkOutTime: '2025-07-05T17:05:00Z',
      checkOutLocation: { lat: -26.1461, lng: 28.0438, accuracy: 10, timestamp: '2025-07-05T17:05:00Z' },
      checkOutSelfie: 'mock://selfie2_out.jpg',
      totalHours: 7.92,
      issues: [
        { id: 'i-1', type: 'late', note: 'Arrived 10 mins late', loggedBy: 'sup-001', loggedAt: '2025-07-05T09:10:00Z' }
      ],
      supervisorRating: 3,
      status: 'pending_approval',
    },
    grossPay: 800,
    deductions: 50,
    netPay: 750,
    status: 'pending_approval',
  },
  // Scheduled shift (upcoming)
  {
    id: 's-003',
    jobId: 'j-003',
    promoterId: 'p-001',
    attendance: {
      shiftId: 's-003',
      promoterId: 'p-001',
      jobId: 'j-003',
      issues: [],
      status: 'scheduled',
    },
    status: 'scheduled',
  },
  // Checked-in shift (active)
  {
    id: 's-004',
    jobId: 'j-004',
    promoterId: 'p-001',
    attendance: {
      shiftId: 's-004',
      promoterId: 'p-001',
      jobId: 'j-004',
      checkInTime: new Date().toISOString(), // today
      checkInLocation: { lat: -26.1778, lng: 28.1214, accuracy: 10, timestamp: new Date().toISOString() },
      checkInSelfie: 'mock://selfie_live.jpg',
      issues: [],
      status: 'checked_in',
    },
    status: 'checked_in',
  },
  // Checked-out shift (pending calculation)
  {
    id: 's-005',
    jobId: 'j-006',
    promoterId: 'p-001',
    attendance: {
      shiftId: 's-005',
      promoterId: 'p-001',
      jobId: 'j-006',
      checkInTime: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
      checkInLocation: { lat: -33.9055, lng: 18.4197, accuracy: 8, timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString() },
      checkInSelfie: 'mock://selfie_checkin.jpg',
      checkOutTime: new Date().toISOString(),
      checkOutLocation: { lat: -33.9055, lng: 18.4197, accuracy: 8, timestamp: new Date().toISOString() },
      checkOutSelfie: 'mock://selfie_checkout.jpg',
      totalHours: 8,
      issues: [],
      status: 'checked_out',
    },
    status: 'checked_out',
  },
  // No-show shift for p-002
  {
    id: 's-006',
    jobId: 'j-007',
    promoterId: 'p-002',
    attendance: {
      shiftId: 's-006',
      promoterId: 'p-002',
      jobId: 'j-007',
      issues: [{ id: 'i-2', type: 'other', note: 'No-show', loggedBy: 'admin-001', loggedAt: '2025-06-25T12:15:00Z' }],
      status: 'no_show',
    },
    status: 'no_show',
  },
];

// ─── Payments ─────────────────────────────────────────────────────────────────
// Payments for various shifts, covering all payment statuses
export const MOCK_PAYMENTS: Payment[] = [
  // Paid payment
  {
    id: 'pay-001',
    shiftId: 's-001',
    promoterId: 'p-001',
    grossAmount: 486,
    deductions: 0,
    netAmount: 486,
    status: 'paid',
    approvedBy: 'admin-001',
    approvedAt: '2025-06-29T10:00:00Z',
    paidAt: '2025-06-30T09:00:00Z',
    reference: 'HGP-20250630-001',
    createdAt: '2025-06-28T22:10:00Z',
  },
  // Pending payment
  {
    id: 'pay-002',
    shiftId: 's-002',
    promoterId: 'p-001',
    grossAmount: 800,
    deductions: 50,
    netAmount: 750,
    status: 'pending',
    createdAt: '2025-07-05T17:10:00Z',
  },
  // Approved (but not paid) payment
  {
    id: 'pay-003',
    shiftId: 's-004',
    promoterId: 'p-001',
    grossAmount: 760, // 8 hours * 95
    deductions: 0,
    netAmount: 760,
    status: 'approved',
    approvedBy: 'admin-001',
    approvedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  // Processing payment
  {
    id: 'pay-004',
    shiftId: 's-005',
    promoterId: 'p-001',
    grossAmount: 1200, // 8 hours * 150
    deductions: 0,
    netAmount: 1200,
    status: 'processing',
    createdAt: new Date().toISOString(),
  },
  // Failed payment
  {
    id: 'pay-005',
    shiftId: 's-006',
    promoterId: 'p-002',
    grossAmount: 550, // 5 hours * 110
    deductions: 0,
    netAmount: 550,
    status: 'failed',
    createdAt: '2025-06-25T20:00:00Z',
  },
];