ALTER TABLE users ADD COLUMN IF NOT EXISTS "streetNumber" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "streetName"   TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "suburb"       TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "postalCode"   TEXT;