// ─── jobsData.ts ─────────────────────────────────────────────────────────────
// Single source of truth for all 24 base jobs.
// Import from here in CRUDJobsLogic, LandingPage, JobsPage, adminDashboard etc.
// ─────────────────────────────────────────────────────────────────────────────

const GL  = '#E8A820'
const G   = '#C4973A'
const G2  = '#AB8D3F'
const G3  = '#D4880A'
const G4  = '#8B5A1A'

export const ACCENT_PALETTE = [GL, G3, G2, G, G4, GL, G3, G2, G, G4, GL, G3, G2, G, G4, GL, G3, G2, G, G4, GL, G3, G2, G]

export const ALL_JOBS = [
  {
    id: 'JB-201', title: 'Brand Promoter — Castle Lager Launch',
    company: 'SABMiller SA', companyInitial: 'S', companyColor: GL,
    location: 'Sandton City, Johannesburg', type: 'Brand Activation',
    pay: 'R 950', payPer: 'per shift', date: 'Sat 22 Mar 2026',
    jobDate: '2026-03-22', approvedAt: '2026-03-10',
    slots: 6, slotsLeft: 2, duration: '8 hrs',
    tags: ['Female preferred', 'English', 'Own transport'],
    accentLine: GL, gradient: `linear-gradient(135deg, rgba(232,168,32,0.10) 0%, rgba(196,151,58,0.04) 100%)`,
    status: 'open',
    contactPerson: 'Thandi Nkosi', contactEmail: 'thandi@sabmiller.co.za', contactPhone: '+27 11 555 0201',
    companyReg: '1895/000583/06', vatNumber: '4560123456', address: '65 Park Lane, Sandton, 2196',
    terms: `1. ENGAGEMENT TERMS\nSABMiller SA engages the Promoter as an independent contractor for the above-referenced campaign.\n\n2. PAYMENT\nPayment of R 950 per shift will be processed within 5 business days of shift completion, subject to successful geo-verified check-in and check-out and supervisor sign-off.\n\n3. CONDUCT & UNIFORM\nThe Promoter agrees to wear the provided branded uniform and comply with all venue rules.\n\n4. LIABILITY\nSABMiller SA is NOT liable for: personal injury due to Promoter negligence, loss of personal property, or travel costs.\n\n5. POPIA COMPLIANCE\nAll personal data is processed in accordance with POPIA.`,
  },
  {
    id: 'JB-202', title: 'Red Bull Sampling — Activations Team',
    company: 'Red Bull South Africa', companyInitial: 'R', companyColor: G3,
    location: 'V&A Waterfront, Cape Town', type: 'Sampling',
    pay: 'R 800', payPer: 'per shift', date: 'Sun 23 Mar 2026',
    jobDate: '2026-03-23', approvedAt: '2026-03-09',
    slots: 4, slotsLeft: 4, duration: '6 hrs',
    tags: ['Any gender', 'Afrikaans + English', 'High energy'],
    accentLine: G3, gradient: `linear-gradient(135deg, rgba(212,136,10,0.10) 0%, rgba(196,151,58,0.04) 100%)`,
    status: 'open',
    contactPerson: 'Marco van der Berg', contactEmail: 'marco@redbull.co.za', contactPhone: '+27 21 555 0202',
    companyReg: '2001/012345/07', vatNumber: '4561234567', address: 'Clock Tower, V&A Waterfront, Cape Town, 8001',
    terms: `1. ENGAGEMENT TERMS\nRed Bull South Africa engages the Promoter as an independent contractor.\n\n2. PAYMENT\nR 800 per shift payable within 5 business days.\n\n3. POPIA COMPLIANCE\nPersonal data processed in accordance with POPIA.`,
  },
  {
    id: 'JB-203', title: 'In-Store Promoter — Shoprite Durban',
    company: 'FreshBrands Ltd', companyInitial: 'F', companyColor: G2,
    location: 'Musgrave Centre, Durban', type: 'In-Store',
    pay: 'R 700', payPer: 'per shift', date: 'Mon 24 – Fri 28 Mar 2026',
    jobDate: '2026-03-28', approvedAt: '2026-03-08',
    slots: 3, slotsLeft: 1, duration: '5 hrs/day x 5 days',
    tags: ['Female', 'Zulu + English', 'Neat appearance'],
    accentLine: G2, gradient: `linear-gradient(135deg, rgba(171,141,63,0.10) 0%, rgba(196,151,58,0.04) 100%)`,
    status: 'filling fast',
    contactPerson: 'Nomvula Dlamini', contactEmail: 'nomvula@freshbrands.co.za', contactPhone: '+27 31 555 0203',
    companyReg: '2010/098765/07', vatNumber: '4562345678', address: '12 Brand Street, Umhlanga, Durban, 4320',
    terms: `1. ENGAGEMENT TERMS\nFreshBrands Ltd engages the Promoter as an independent contractor for in-store promotions.\n\n2. PAYMENT\nR 700 per shift totalling R 3,500 for 5 days. Processed within 7 business days.\n\n3. POPIA COMPLIANCE\nData processed in accordance with POPIA.`,
  },
  {
    id: 'JB-204', title: 'Event Hostess — Menlyn Fashion Night',
    company: 'Acme Events Corp', companyInitial: 'A', companyColor: GL,
    location: 'Menlyn Mall, Pretoria', type: 'Events & Hosting',
    pay: 'R 1,200', payPer: 'per shift', date: 'Fri 21 Mar 2026',
    jobDate: '2026-03-21', approvedAt: '2026-03-07',
    slots: 8, slotsLeft: 3, duration: '10 hrs',
    tags: ['Female', '1.70m+', 'Smart evening wear provided'],
    accentLine: GL, gradient: `linear-gradient(135deg, rgba(232,168,32,0.12) 0%, rgba(196,151,58,0.04) 100%)`,
    status: 'open',
    contactPerson: 'Pieter Joubert', contactEmail: 'pieter@acmeevents.co.za', contactPhone: '+27 12 555 0204',
    companyReg: '2005/056789/07', vatNumber: '4563456789', address: '44 Corporate Park, Centurion, 0157',
    terms: `1. ENGAGEMENT TERMS\nAcme Events Corp engages the Promoter as an independent contractor for event hosting.\n\n2. PAYMENT\nR 1,200 per 10-hour shift. Overtime beyond 10 hours at R 150/hr.\n\n3. POPIA COMPLIANCE\nAll data handled in accordance with POPIA.`,
  },
  {
    id: 'JB-205', title: 'Heineken Roadshow — Weekend Crew',
    company: 'Heineken SA', companyInitial: 'H', companyColor: G3,
    location: 'Mall of Africa, Midrand', type: 'Brand Activation',
    pay: 'R 880', payPer: 'per shift', date: 'Sat 29 Mar 2026',
    jobDate: '2026-03-29', approvedAt: '2026-03-11',
    slots: 5, slotsLeft: 5, duration: '8 hrs',
    tags: ['Any gender', 'English', 'Brand experience'],
    accentLine: G3, gradient: `linear-gradient(135deg, rgba(212,136,10,0.10) 0%, rgba(196,151,58,0.04) 100%)`,
    status: 'open',
    contactPerson: 'Jason Ferreira', contactEmail: 'jason@heineken.co.za', contactPhone: '+27 11 555 0205',
    companyReg: '1998/034567/06', vatNumber: '4564567890', address: '90 Brewery Road, Midrand, 1685',
    terms: `1. ENGAGEMENT TERMS\nHeineken SA engages the Promoter as an independent contractor.\n\n2. AGE VERIFICATION\nThe Promoter must NOT distribute Heineken products to anyone under 18.\n\n3. PAYMENT\nR 880 per 8-hour shift.\n\n4. POPIA COMPLIANCE\nData handled in accordance with POPIA.`,
  },
  {
    id: 'JB-206', title: 'Vodacom Product Demo — Weekend Staff',
    company: 'Vodacom SA', companyInitial: 'V', companyColor: G2,
    location: 'Canal Walk, Cape Town', type: 'In-Store',
    pay: 'R 750', payPer: 'per shift', date: 'Sun 30 Mar 2026',
    jobDate: '2026-03-30', approvedAt: '2026-03-11',
    slots: 4, slotsLeft: 4, duration: '6 hrs',
    tags: ['Any gender', 'Tech savvy', 'English'],
    accentLine: G2, gradient: `linear-gradient(135deg, rgba(171,141,63,0.10) 0%, rgba(196,151,58,0.04) 100%)`,
    status: 'open',
    contactPerson: 'Siphiwe Mthembu', contactEmail: 'siphiwe@vodacom.co.za', contactPhone: '+27 21 555 0206',
    companyReg: '1993/003367/06', vatNumber: '4565678901', address: 'Vodacom Park, Canal Walk, Cape Town, 7441',
    terms: `1. ENGAGEMENT TERMS\nVodacom SA engages the Promoter as an independent contractor to demonstrate products.\n\n2. DEVICE HANDLING\nDemo devices are the property of Vodacom SA. Loss or damage due to negligence will be invoiced.\n\n3. PAYMENT\nR 750 per shift.\n\n4. POPIA COMPLIANCE\nData handled in accordance with POPIA.`,
  },
  {
    id: 'JB-207', title: "Nando's In-Store Tasting — Joburg North",
    company: "Nando's SA", companyInitial: 'N', companyColor: G,
    location: 'Fourways Mall, Johannesburg', type: 'In-Store',
    pay: 'R 680', payPer: 'per shift', date: 'Sat 29 Mar 2026',
    jobDate: '2026-03-29', approvedAt: '2026-03-10',
    slots: 2, slotsLeft: 1, duration: '5 hrs',
    tags: ['Female preferred', 'Energetic', 'English + Zulu'],
    accentLine: G, gradient: `linear-gradient(135deg, rgba(196,151,58,0.10) 0%, rgba(171,141,63,0.04) 100%)`,
    status: 'filling fast',
    contactPerson: 'Ayanda Khumalo', contactEmail: 'ayanda@nandos.co.za', contactPhone: '+27 11 555 0207',
    companyReg: '1987/007890/06', vatNumber: '4566789012', address: '3 Nandos House, Midrand, 1682',
    terms: `1. ENGAGEMENT TERMS\nNando's SA engages the Promoter as an independent contractor for in-store food tasting.\n\n2. FOOD HYGIENE\nGloves must be worn at all times when handling product.\n\n3. PAYMENT\nR 680 per 5-hour shift.\n\n4. POPIA COMPLIANCE\nData handled in accordance with POPIA.`,
  },
  {
    id: 'JB-208', title: 'MTN Brand Ambassador — Soweto Festival',
    company: 'MTN SA', companyInitial: 'M', companyColor: GL,
    location: 'Maponya Mall, Soweto', type: 'Brand Activation',
    pay: 'R 900', payPer: 'per shift', date: 'Sat 5 Apr 2026',
    jobDate: '2026-04-05', approvedAt: '2026-03-11',
    slots: 10, slotsLeft: 7, duration: '8 hrs',
    tags: ['Any gender', 'Sesotho + English', 'Brand activation exp'],
    accentLine: GL, gradient: `linear-gradient(135deg, rgba(232,168,32,0.10) 0%, rgba(196,151,58,0.04) 100%)`,
    status: 'open',
    contactPerson: 'Lerato Mokoena', contactEmail: 'lerato@mtn.co.za', contactPhone: '+27 11 555 0208',
    companyReg: '1994/009555/06', vatNumber: '4567890123', address: '216 14th Avenue, Johannesburg, 2091',
    terms: `1. ENGAGEMENT TERMS\nMTN SA engages the Promoter as an independent contractor.\n\n2. PAYMENT\nR 900 per shift.\n\n3. POPIA COMPLIANCE\nData handled in accordance with POPIA.`,
  },
  {
    id: 'JB-209', title: 'Tiger Brands — Pick n Pay Sampling',
    company: 'Tiger Brands', companyInitial: 'T', companyColor: G3,
    location: 'Greenacres, Port Elizabeth', type: 'Sampling',
    pay: 'R 650', payPer: 'per shift', date: 'Mon 31 Mar 2026',
    jobDate: '2026-03-31', approvedAt: '2026-03-09',
    slots: 3, slotsLeft: 2, duration: '5 hrs',
    tags: ['Female', 'isiXhosa + English', 'Neat appearance'],
    accentLine: G3, gradient: `linear-gradient(135deg, rgba(212,136,10,0.10) 0%, rgba(196,151,58,0.04) 100%)`,
    status: 'open',
    contactPerson: 'Bongiwe Ntuli', contactEmail: 'bongiwe@tigerbrands.co.za', contactPhone: '+27 41 555 0209',
    companyReg: '1921/000570/06', vatNumber: '4568901234', address: '3010 William Nicol Drive, Johannesburg, 2021',
    terms: `1. ENGAGEMENT TERMS\nTiger Brands engages the Promoter as an independent contractor for sampling duties.\n\n2. PAYMENT\nR 650 per 5-hour shift.\n\n3. POPIA COMPLIANCE\nData handled in accordance with POPIA.`,
  },
  {
    id: 'JB-210', title: 'Absolut Vodka — Night Activation',
    company: 'Pernod Ricard SA', companyInitial: 'P', companyColor: G4,
    location: 'Rosebank, Johannesburg', type: 'Events & Hosting',
    pay: 'R 1,100', payPer: 'per shift', date: 'Fri 28 Mar 2026',
    jobDate: '2026-03-28', approvedAt: '2026-03-10',
    slots: 6, slotsLeft: 2, duration: '7 hrs',
    tags: ['Female', '21+', 'Evening wear', 'English'],
    accentLine: G4, gradient: `linear-gradient(135deg, rgba(139,90,26,0.12) 0%, rgba(107,63,16,0.06) 100%)`,
    status: 'filling fast',
    contactPerson: 'Claire Beaumont', contactEmail: 'claire@pernodricard.co.za', contactPhone: '+27 11 555 0210',
    companyReg: '1999/088341/07', vatNumber: '4569012345', address: '54 Wessel Road, Rivonia, 2128',
    terms: `1. ENGAGEMENT TERMS\nPernod Ricard SA engages the Promoter as an independent contractor. Promoters must be 21+.\n\n2. ALCOHOL SERVICE\nThe Promoter must not consume alcohol during the shift. Age verification required.\n\n3. PAYMENT\nR 1,100 per 7-hour shift.\n\n4. POPIA COMPLIANCE\nData handled in accordance with POPIA.`,
  },
  {
    id: 'JB-211', title: 'Shoprite Checkers — Easter Promotions',
    company: 'Shoprite Holdings', companyInitial: 'S', companyColor: G2,
    location: 'Westgate Mall, Johannesburg', type: 'In-Store',
    pay: 'R 700', payPer: 'per shift', date: 'Thu 3 Apr – Sun 6 Apr 2026',
    jobDate: '2026-04-06', approvedAt: '2026-03-11',
    slots: 8, slotsLeft: 6, duration: '6 hrs/day x 4 days',
    tags: ['Female preferred', 'Sesotho or Zulu', 'Reliable'],
    accentLine: G2, gradient: `linear-gradient(135deg, rgba(171,141,63,0.10) 0%, rgba(196,151,58,0.04) 100%)`,
    status: 'open',
    contactPerson: 'Zanele Sithole', contactEmail: 'zanele@shoprite.co.za', contactPhone: '+27 11 555 0211',
    companyReg: '1936/007721/06', vatNumber: '4570123456', address: 'Shoprite House, William Dabs Street, Cape Town, 8001',
    terms: `1. ENGAGEMENT TERMS\nShoprite Holdings engages the Promoter as an independent contractor.\n\n2. PAYMENT\nR 700 per 6-hour shift (R 2,800 total). Processed within 7 business days.\n\n3. POPIA COMPLIANCE\nData handled in accordance with POPIA.`,
  },
  {
    id: 'JB-212', title: 'Coca-Cola Spaza Activation — Khayelitsha',
    company: 'Coca-Cola SA', companyInitial: 'C', companyColor: G,
    location: 'Khayelitsha, Cape Town', type: 'Sampling',
    pay: 'R 750', payPer: 'per shift', date: 'Sat 4 Apr 2026',
    jobDate: '2026-04-04', approvedAt: '2026-03-10',
    slots: 5, slotsLeft: 5, duration: '7 hrs',
    tags: ['Any gender', 'isiXhosa + English', 'Community-facing'],
    accentLine: G, gradient: `linear-gradient(135deg, rgba(196,151,58,0.10) 0%, rgba(171,141,63,0.04) 100%)`,
    status: 'open',
    contactPerson: 'Lungelo Mgqibi', contactEmail: 'lungelo@coca-cola.co.za', contactPhone: '+27 21 555 0212',
    companyReg: '1902/000012/06', vatNumber: '4571234567', address: '3 Buitenkant Street, Cape Town, 8001',
    terms: `1. ENGAGEMENT TERMS\nCoca-Cola SA engages the Promoter as an independent contractor for community sampling.\n\n2. PAYMENT\nR 750 per 7-hour shift.\n\n3. POPIA COMPLIANCE\nData handled in accordance with POPIA.`,
  },
  {
    id: 'JB-213', title: 'Woolworths Food Tasting — Upper-End Malls',
    company: 'Woolworths SA', companyInitial: 'W', companyColor: GL,
    location: 'Cavendish Square, Cape Town', type: 'In-Store',
    pay: 'R 850', payPer: 'per shift', date: 'Sat 5 Apr 2026',
    jobDate: '2026-04-05', approvedAt: '2026-03-11',
    slots: 3, slotsLeft: 3, duration: '6 hrs',
    tags: ['Female', 'Well-spoken', 'English + Afrikaans', 'Neat'],
    accentLine: GL, gradient: `linear-gradient(135deg, rgba(232,168,32,0.10) 0%, rgba(196,151,58,0.04) 100%)`,
    status: 'open',
    contactPerson: 'Mia van Wyk', contactEmail: 'mia@woolworths.co.za', contactPhone: '+27 21 555 0213',
    companyReg: '1952/003403/06', vatNumber: '4572345678', address: 'Woolworths House, 93 Longmarket Street, Cape Town, 8001',
    terms: `1. ENGAGEMENT TERMS\nWoolworths SA engages the Promoter as an independent contractor for premium food tasting.\n\n2. PAYMENT\nR 850 per 6-hour shift.\n\n3. POPIA COMPLIANCE\nData handled in accordance with POPIA.`,
  },
  {
    id: 'JB-214', title: "Jack Daniel's Whisky Night — Durban",
    company: 'Brown-Forman SA', companyInitial: 'B', companyColor: G4,
    location: 'uShaka Marine, Durban', type: 'Events & Hosting',
    pay: 'R 1,050', payPer: 'per shift', date: 'Fri 4 Apr 2026',
    jobDate: '2026-04-04', approvedAt: '2026-03-09',
    slots: 5, slotsLeft: 3, duration: '8 hrs',
    tags: ['Female', 'Afrikaans or Zulu + English', '21+', 'Brand exp'],
    accentLine: G4, gradient: `linear-gradient(135deg, rgba(139,90,26,0.12) 0%, rgba(107,63,16,0.06) 100%)`,
    status: 'open',
    contactPerson: 'Ruan Kotze', contactEmail: 'ruan@brown-forman.co.za', contactPhone: '+27 31 555 0214',
    companyReg: '2000/099123/07', vatNumber: '4573456789', address: '14 Harbour Road, Durban, 4001',
    terms: `1. ENGAGEMENT TERMS\nBrown-Forman SA engages the Promoter as an independent contractor. Minimum age 21.\n\n2. PAYMENT\nR 1,050 per 8-hour shift.\n\n3. POPIA COMPLIANCE\nData handled in accordance with POPIA.`,
  },
  {
    id: 'JB-215', title: 'Sanlam Financial Services Fair',
    company: 'Sanlam Group', companyInitial: 'S', companyColor: G3,
    location: 'CTICC, Cape Town', type: 'Events & Hosting',
    pay: 'R 900', payPer: 'per shift', date: 'Wed 8 Apr 2026',
    jobDate: '2026-04-08', approvedAt: '2026-03-11',
    slots: 6, slotsLeft: 6, duration: '9 hrs',
    tags: ['Any gender', 'Corporate appearance', 'Afrikaans + English'],
    accentLine: G3, gradient: `linear-gradient(135deg, rgba(212,136,10,0.10) 0%, rgba(196,151,58,0.04) 100%)`,
    status: 'open',
    contactPerson: 'Werner du Plessis', contactEmail: 'werner@sanlam.co.za', contactPhone: '+27 21 555 0215',
    companyReg: '1959/001562/06', vatNumber: '4574567890', address: '2 Strand Road, Bellville, Cape Town, 7530',
    terms: `1. ENGAGEMENT TERMS\nSanlam Group engages the Promoter as an independent contractor.\n\n2. FINANCIAL ADVICE PROHIBITION\nThe Promoter may NOT provide financial advice.\n\n3. PAYMENT\nR 900 per 9-hour shift.\n\n4. POPIA COMPLIANCE\nStrict POPIA compliance required.`,
  },
  {
    id: 'JB-216', title: 'Listerine Sampling — Taxi Ranks',
    company: 'Johnson & Johnson SA', companyInitial: 'J', companyColor: G2,
    location: 'Noord Taxi Rank, Johannesburg', type: 'Sampling',
    pay: 'R 620', payPer: 'per shift', date: 'Tue 7 Apr 2026',
    jobDate: '2026-04-07', approvedAt: '2026-03-08',
    slots: 8, slotsLeft: 8, duration: '5 hrs',
    tags: ['Female', 'Zulu + English', 'Community-facing', 'Resilient'],
    accentLine: G2, gradient: `linear-gradient(135deg, rgba(171,141,63,0.10) 0%, rgba(196,151,58,0.04) 100%)`,
    status: 'open',
    contactPerson: 'Thandiwe Mhlongo', contactEmail: 'thandiwe@jnj.co.za', contactPhone: '+27 11 555 0216',
    companyReg: '1968/004567/06', vatNumber: '4575678901', address: '7 Hunts End, Randburg, 2194',
    terms: `1. ENGAGEMENT TERMS\nJohnson & Johnson SA engages the Promoter as an independent contractor.\n\n2. PAYMENT\nR 620 per 5-hour shift.\n\n3. POPIA COMPLIANCE\nData handled in accordance with POPIA.`,
  },
  {
    id: 'JB-217', title: 'KFC New Menu Launch — Gauteng',
    company: 'KFC South Africa', companyInitial: 'K', companyColor: G,
    location: 'Jabulani Mall, Soweto', type: 'Brand Activation',
    pay: 'R 780', payPer: 'per shift', date: 'Thu 9 Apr 2026',
    jobDate: '2026-04-09', approvedAt: '2026-03-10',
    slots: 4, slotsLeft: 4, duration: '6 hrs',
    tags: ['Any gender', 'Energetic', 'English + Sesotho'],
    accentLine: G, gradient: `linear-gradient(135deg, rgba(196,151,58,0.10) 0%, rgba(171,141,63,0.04) 100%)`,
    status: 'open',
    contactPerson: 'Tebogo Radebe', contactEmail: 'tebogo@kfc.co.za', contactPhone: '+27 11 555 0217',
    companyReg: '1971/006345/06', vatNumber: '4576789012', address: '1 Harrington Street, Cape Town, 8001',
    terms: `1. ENGAGEMENT TERMS\nKFC South Africa engages the Promoter as an independent contractor.\n\n2. PAYMENT\nR 780 per 6-hour shift.\n\n3. POPIA COMPLIANCE\nData handled in accordance with POPIA.`,
  },
  {
    id: 'JB-218', title: 'Hyundai Test Drive — Weekend Promoter',
    company: 'Hyundai Automotive SA', companyInitial: 'H', companyColor: G3,
    location: 'Menlyn Park, Pretoria', type: 'Events & Hosting',
    pay: 'R 950', payPer: 'per shift', date: 'Sat 12 Apr 2026',
    jobDate: '2026-04-12', approvedAt: '2026-03-11',
    slots: 3, slotsLeft: 3, duration: '8 hrs',
    tags: ['Female preferred', '1.65m+', 'Automotive knowledge a plus'],
    accentLine: G3, gradient: `linear-gradient(135deg, rgba(212,136,10,0.10) 0%, rgba(196,151,58,0.04) 100%)`,
    status: 'open',
    contactPerson: 'Andile Nxumalo', contactEmail: 'andile@hyundai.co.za', contactPhone: '+27 12 555 0218',
    companyReg: '2002/011234/07', vatNumber: '4577890123', address: 'Hyundai Automotive House, Centurion, 0157',
    terms: `1. ENGAGEMENT TERMS\nHyundai Automotive SA engages the Promoter as an independent contractor.\n\n2. VEHICLE PROXIMITY\nThe Promoter must not enter or operate any display vehicles.\n\n3. PAYMENT\nR 950 per 8-hour shift.\n\n4. POPIA COMPLIANCE\nData handled in accordance with POPIA.`,
  },
  {
    id: 'JB-219', title: 'Old Mutual Roadshow — PE & East London',
    company: 'Old Mutual SA', companyInitial: 'O', companyColor: G2,
    location: 'The Boardwalk, Port Elizabeth', type: 'Events & Hosting',
    pay: 'R 880', payPer: 'per shift', date: 'Mon 14 Apr 2026',
    jobDate: '2026-04-14', approvedAt: '2026-03-11',
    slots: 4, slotsLeft: 4, duration: '7 hrs',
    tags: ['Any gender', 'Corporate', 'isiXhosa + English'],
    accentLine: G2, gradient: `linear-gradient(135deg, rgba(171,141,63,0.10) 0%, rgba(196,151,58,0.04) 100%)`,
    status: 'open',
    contactPerson: 'Nomsa Qwabe', contactEmail: 'nomsa@oldmutual.co.za', contactPhone: '+27 41 555 0219',
    companyReg: '1845/001000/06', vatNumber: '4578901234', address: 'Mutualpark, Jan Smuts Drive, Cape Town, 7405',
    terms: `1. ENGAGEMENT TERMS\nOld Mutual SA engages the Promoter as an independent contractor.\n\n2. FINANCIAL SERVICES PROHIBITION\nThe Promoter may not provide financial advice.\n\n3. PAYMENT\nR 880 per 7-hour shift.\n\n4. POPIA COMPLIANCE\nStrict POPIA compliance required.`,
  },
  {
    id: 'JB-220', title: 'Unilever — Dove Beauty Sampling',
    company: 'Unilever SA', companyInitial: 'U', companyColor: GL,
    location: 'Gateway Theatre of Shopping, Durban', type: 'Sampling',
    pay: 'R 720', payPer: 'per shift', date: 'Sat 12 Apr 2026',
    jobDate: '2026-04-12', approvedAt: '2026-03-10',
    slots: 5, slotsLeft: 5, duration: '6 hrs',
    tags: ['Female', 'Confident', 'English + Zulu'],
    accentLine: GL, gradient: `linear-gradient(135deg, rgba(232,168,32,0.10) 0%, rgba(196,151,58,0.04) 100%)`,
    status: 'open',
    contactPerson: 'Priya Naidoo', contactEmail: 'priya@unilever.co.za', contactPhone: '+27 31 555 0220',
    companyReg: '1951/000583/06', vatNumber: '4579012345', address: '15 Nollsworth Crescent, La Lucia, Durban, 4051',
    terms: `1. ENGAGEMENT TERMS\nUnilever SA engages the Promoter as an independent contractor.\n\n2. BEAUTY PRODUCT HANDLING\nSamples must not be applied without explicit consent.\n\n3. PAYMENT\nR 720 per 6-hour shift.\n\n4. POPIA COMPLIANCE\nData handled in accordance with POPIA.`,
  },
  {
    id: 'JB-221', title: 'Standard Bank Career Expo — Wits',
    company: 'Standard Bank SA', companyInitial: 'S', companyColor: G3,
    location: 'Wits University, Johannesburg', type: 'Events & Hosting',
    pay: 'R 820', payPer: 'per shift', date: 'Tue 15 Apr 2026',
    jobDate: '2026-04-15', approvedAt: '2026-03-11',
    slots: 6, slotsLeft: 6, duration: '8 hrs',
    tags: ['Any gender', 'Corporate', 'UCT/Wits preferred', 'English'],
    accentLine: G3, gradient: `linear-gradient(135deg, rgba(212,136,10,0.10) 0%, rgba(196,151,58,0.04) 100%)`,
    status: 'open',
    contactPerson: 'Kagiso Motsepe', contactEmail: 'kagiso@standardbank.co.za', contactPhone: '+27 11 555 0221',
    companyReg: '1962/000738/06', vatNumber: '4580123456', address: '9 Simmonds Street, Johannesburg, 2001',
    terms: `1. ENGAGEMENT TERMS\nStandard Bank SA engages the Promoter as an independent contractor.\n\n2. FINANCIAL ADVICE PROHIBITION\nNo banking or financial advice permitted.\n\n3. PAYMENT\nR 820 per 8-hour shift.\n\n4. POPIA COMPLIANCE\nData handled in accordance with POPIA.`,
  },
  {
    id: 'JB-222', title: 'Brutal Fruit — Weekend Sampling Crew',
    company: 'SAB South Africa', companyInitial: 'S', companyColor: G4,
    location: 'Eastgate Mall, Johannesburg', type: 'Sampling',
    pay: 'R 800', payPer: 'per shift', date: 'Sat 19 Apr 2026',
    jobDate: '2026-04-19', approvedAt: '2026-03-11',
    slots: 4, slotsLeft: 4, duration: '7 hrs',
    tags: ['Female preferred', '18-28', 'Energetic', 'Afrikaans a plus'],
    accentLine: G4, gradient: `linear-gradient(135deg, rgba(139,90,26,0.12) 0%, rgba(107,63,16,0.06) 100%)`,
    status: 'open',
    contactPerson: 'Chantelle Botha', contactEmail: 'chantelle@sab.co.za', contactPhone: '+27 11 555 0222',
    companyReg: '1895/000583/06', vatNumber: '4581234567', address: '65 Park Lane, Sandton, 2196',
    terms: `1. ENGAGEMENT TERMS\nSAB South Africa engages the Promoter as an independent contractor.\n\n2. AGE VERIFICATION\nNo alcohol to anyone under 18.\n\n3. PAYMENT\nR 800 per 7-hour shift.\n\n4. POPIA COMPLIANCE\nData handled in accordance with POPIA.`,
  },
  {
    id: 'JB-223', title: 'Pick n Pay Smart Shopper Activation',
    company: 'Pick n Pay SA', companyInitial: 'P', companyColor: G2,
    location: 'Pavilion Shopping Centre, Durban', type: 'Brand Activation',
    pay: 'R 760', payPer: 'per shift', date: 'Wed 16 Apr 2026',
    jobDate: '2026-04-16', approvedAt: '2026-03-10',
    slots: 5, slotsLeft: 5, duration: '6 hrs',
    tags: ['Any gender', 'English + Zulu', 'Retail exp preferred'],
    accentLine: G2, gradient: `linear-gradient(135deg, rgba(171,141,63,0.10) 0%, rgba(196,151,58,0.04) 100%)`,
    status: 'open',
    contactPerson: 'Sibusiso Vilakazi', contactEmail: 'sibusiso@pnp.co.za', contactPhone: '+27 31 555 0223',
    companyReg: '1940/000779/06', vatNumber: '4582345678', address: 'Pick n Pay House, 101 Rosmead Avenue, Cape Town, 7700',
    terms: `1. ENGAGEMENT TERMS\nPick n Pay SA engages the Promoter as an independent contractor.\n\n2. DATA COLLECTION\nExplicit consent required before collecting any customer data.\n\n3. PAYMENT\nR 760 per 6-hour shift.\n\n4. POPIA COMPLIANCE\nStrict POPIA compliance essential.`,
  },
  {
    id: 'JB-224', title: 'Distell Premium Wines — Trade Launch',
    company: 'Distell Group', companyInitial: 'D', companyColor: G3,
    location: 'Sandton Convention Centre, Johannesburg', type: 'Events & Hosting',
    pay: 'R 1,350', payPer: 'per shift', date: 'Thu 17 Apr 2026',
    jobDate: '2026-04-17', approvedAt: '2026-03-11',
    slots: 10, slotsLeft: 7, duration: '10 hrs',
    tags: ['Female', '1.68m+', 'Evening wear provided', 'Wine knowledge a plus'],
    accentLine: G3, gradient: `linear-gradient(135deg, rgba(212,136,10,0.12) 0%, rgba(196,151,58,0.04) 100%)`,
    status: 'open',
    contactPerson: 'Francois du Toit', contactEmail: 'francois@distell.co.za', contactPhone: '+27 11 555 0224',
    companyReg: '1988/005010/06', vatNumber: '4583456789', address: 'Distell Park, Adam Tas Road, Stellenbosch, 7599',
    terms: `1. ENGAGEMENT TERMS\nDistell Group engages the Promoter as an independent contractor for a premium wine trade launch.\n\n2. WINE SERVICE STANDARDS\nStrict adherence to the presentation script is required.\n\n3. PAYMENT\nR 1,350 per 10-hour shift. Overtime at R 150/hr.\n\n4. CONFIDENTIALITY\nAll trade pricing and buyer information is strictly confidential.\n\n5. POPIA COMPLIANCE\nData handled in accordance with POPIA.`,
  },
]

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Merge admin-created jobs (stored in localStorage) with the 24 base jobs */
export function getAllJobsWithAdminJobs(): typeof ALL_JOBS {
  try {
    const stored: any[] = JSON.parse(localStorage.getItem('hg_admin_jobs') || '[]')
    const adminJobs = stored.map((j: any, idx: number) => ({
      ...j,
      companyColor: ACCENT_PALETTE[idx % ACCENT_PALETTE.length],
      accentLine:   ACCENT_PALETTE[idx % ACCENT_PALETTE.length],
      gradient:     `linear-gradient(135deg, rgba(232,168,32,0.10) 0%, rgba(196,151,58,0.04) 100%)`,
    }))
    // Admin jobs override base jobs with same ID; new ones are prepended
    const adminIds = new Set(adminJobs.map((j: any) => j.id))
    const baseFiltered = ALL_JOBS.filter(j => !adminIds.has(j.id))
    return [...adminJobs, ...baseFiltered] as typeof ALL_JOBS
  } catch {
    return ALL_JOBS
  }
}

/** Return only jobs whose event date is today or in the future, sorted newest-approved first */
export function getActiveJobs(allJobs: typeof ALL_JOBS) {
  const today = new Date()
  today.setHours(0, 0, 0, 0)
  return allJobs
    .filter(j => new Date(j.jobDate) >= today)
    .sort((a, b) => {
      const d = new Date(b.approvedAt).getTime() - new Date(a.approvedAt).getTime()
      if (d !== 0) return d
      return new Date(a.jobDate).getTime() - new Date(b.jobDate).getTime()
    })
}